SM.Web/ViewModels/B07_zgloViewModels/B07_zgloEditViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using SM.Infrastructure.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SM.Web.ViewModels.B07_zgloViewModels
{
    public class B07_zgloEditViewModel
    {
        public B07_zgloDTO B07_ZgloDTO { get; set; }
        public SelectList Administracje { get; set; }
        public SelectList Branze { get; set; }
        public SelectList Pracownicy { get; set; }
    }
}

SM.Web/Controllers/Adresy/AdministracjeController.cs
using Microsoft.AspNetCore.Mvc;
using SM.Infrastructure.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SM.Web.Controllers.Adresy
{
    public class AdministracjeController : Controller
    {
        private readonly IAdresService _administracjeService;

        public AdministracjeController(IAdresService administracjeService)
        {
            _administracjeService = administracjeService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int pageIndex = 1, int pageSize = 10)
        {
            var b07_zgloList = await _administracjeService.BrowseAdmAsync(pageIndex, pageSize);

            return View(b07_zgloList);
        }
    }
}

SM.Web/Controllers/B07_zgloController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SM.Infrastructure.DTO;
using SM.Infrastructure.Services;
using SM.Web.ViewModels;
using SM.Web.ViewModels.B07_zgloViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SM.Web.Controllers
{
    public class B07_zgloController : Controller
    {
        private readonly IB07_zgloService _b07_zgloService;
        private readonly IAdresService _administracjeService;

        public B07_zgloController(IB07_zgloService b07_zgloService, IAdresService administracjeService)
        {
            _b07_zgloService = b07_zgloService;
            _administracjeService = administracjeService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string sortOrder = "numer_zglo", bool orderAsc = true, int pageIndex = 1, int pageSize = 10)
        {
            var b07_zgloList = await _b07_zgloService.BrowseAsync(sortOrder, orderAsc, pageIndex, pageSize);

            return View(b07_zgloList);
        }

        public async Task<IActionResult> Create()
        {
            if(ModelState.IsValid)
            {
                var noweIdB07_zglo = await _b07_zgloService.AddAsync();

                return RedirectToAction("Edit", new { id = noweIdB07_zglo });
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if(ModelState.IsValid)
            {
                var b07_zgloObj = await _b07_zgloService.GetZgloAsync(id);
                var administracje = await _administracjeService.GetAllAdmAsync();
                var branze = await _administracjeService.GetAllBranzeAsync();
                var pracownicy = await _administracjeService.GetAllPracownicyAsync();
                var vm = new B07_zgloEditViewModel
                {
                    B07_ZgloDTO = b07_zgloObj,
                    Administracje = new SelectList(administracje, "id_admi", "nazwa"),
                    Branze = new SelectList(branze, "nr_branzy", "nazwa_bran"),
                    Pracownicy = new SelectList(pracownicy, "nr_osoby", "nazwisko")
                };

                return View(vm);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(B07_zgloEditViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var zgloszenie = vm.B07_ZgloDTO;
                await _b07_zgloService.UpdateAsync(zgloszenie, zgloszenie.B07_zgloId);

                return RedirectToAction("Index");
            }

            var administracje = await _administracjeService.GetAllAdmAsync();
            var branze = await _administracjeService.GetAllBranzeAsync();
            var pracownicy = await _administracjeService.GetAllPracownicyAsync();
            vm.Administracje = new SelectList(administracje, "id_admi", "nazwa");
            vm.Branze = new SelectList(branze, "nr_branzy", "nazwa_bran");
            vm.Pracownicy = new SelectList(pracownicy, "nr_osoby", "nazwisko");

            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var b07_zgloObj = await _b07_zgloService.GetZgloAsync(id);

            return PartialView(b07_zgloObj);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _b07_zgloService.RemoveAsync(id);

            return Json(Url.Action("Index"));
        }

        //pomocnicze
        public async Task<IActionResult> GetBudynki()
        {
            var budynkiDb = await _administracjeService.GetAllBudAsync();

            return Json(budynkiDb);
        }

        public async Task<IActionResult> GetKlatki(string budynekId)
        {
            var klatkiDb = await _administracjeService.GetKlatkiAsync(budynekId);

            return Json(klatkiDb);
        }

        public async Task<IActionResult> GetLokale(string klatkaId, string budynekId)
        {
            var lokaleDb = await _administracjeService.GetLokaleAsync(klatkaId, budynekId);

            return Json(lokaleDb);
        }

        public async Task<IActionResult> UtworzAdresString(string budynekId = "", string klatkaId = "", string lokalId = "")
        {
            var adres = await _administracjeService.CreateStringAddress(budynekId, klatkaId, lokalId);

            return Json(adres);
        }

        public async Task<IActionResult> FindAddressFromString(string adres)
        {
            var wynik = await _administracjeService.FindAddressFromString(adres);

            return Json(wynik);
        }
    }
}

SM.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoMapper.Configuration;
using Microsoft.AspNetCore.Builder;
using SM.Infrastructure.Settings;
using Autofac;
using SM.Core.Repositories;
using SM.Infrastructure.EF;
using SM.Core.Paging;

namespace SM.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IB07_zgloRepository _repo;

        public HomeController(IB07_zgloRepository repo)
        {
            _repo = repo;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

    }
}

SM.Web/Views/B07_zglo/Details.cshtml
@model SM.Infrastructure.DTO.B07_zgloDTO

@{
    Layout = "";
}

<style>
    .detailsWrap {
        word-wrap: break-word;
    }
</style>

<!-- Modal content-->
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Szczegóły zgłoszenia: @Model.numer_zglo </h4>
        </div>
        <div class="modal-body">
            <div class="container-fluid">
                <div class="col-md-12 detailsWrap">

                    <h3><b>Moduł wprowadzania usterki:</b></h3>

                    <b>Administracja</b>
                    <br />
                    <!--poprawic zeby nie bylo id a string-->
                    @Html.DisplayFor(model => model.id_admin)
                    <br />
                    <b>Numer zgłoszenia</b>
                    <br />
                    @Html.DisplayFor(model => model.numer_zglo)
                    <br />
                    <b>Branża</b>
                    <br />
                    <!--poprawic zeby nie bylo id a string-->
                    @Html.DisplayFor(model => model.id_branz)
                    <br />
                    <b>Data zgłoszenia</b>
                    <br />
                    @Html.DisplayFor(model => model.data_zglos)
                    <br />
                    <b>Nazwisko zgłaszającego</b>
                    <br />
                    @Html.DisplayFor(model => model.nazwisko)
                    <br />
                    <b>Adres</b>
                    <br />
                    <!--poprawic zeby nie bylo id a string-->
                    @Html.DisplayFor(model => model.id_adres)
                    <br />
                    <b>Rodzaj usterki</b>
                    <br />
                    @Html.DisplayFor(model => model.rodzaj_ust)

                    <h3><b>Moduł inspektora:</b></h3>

                    <b>Inspektor</b>
                    <br />
                    <!--poprawic zeby nie bylo id a string-->
                    @Html.DisplayFor(model => model.inspektor)
                    <br />
                    <b>Data akceptacji inspektora</b>
                    <br />
                    @Html.DisplayFor(model => model.data_insp)
                    <br />
                    <b>Wykonawca</b>
                    <br />
                    @Html.DisplayFor(model => model.wykonawca)
                    <br />
                    <b>Wykonawca zewnętrzny</b>
                    <br />
                    @Html.DisplayFor(model => model.wykon_zewn)

                    <h3><b>Moduł wprowadzania usterki:</b></h3>

                    <b>Numer zlecenia</b>
                    <br />
                    @Html.DisplayFor(model => model.numer_zlec)
                    <br />
                    <b>Data zlecenia</b>
                    <br />
                    @Html.DisplayFor(model => model.data_zlec)
                    <br />
                    <b>Pracownik</b>
                    <br />
                    <!--poprawic zeby nie bylo id a string-->
                    @Html.DisplayFor(model => model.nr_prac)
                    <br />
                    <b>Opis wykonania</b>
                    @Html.DisplayFor(model => model.opis_wykon)
                    <br />
                    <b>Uwagi</b>
                    <br />
                    @Html.DisplayFor(model => model.uwagi_wyko)
                    <br />
                    <b>Uwagi dodatkowe</b>
                    <br />
                    @Html.DisplayFor(model => model.uwagi1)
                    <br />
                    <b>Termin realizacji</b>
                    <br />
                    @Html.DisplayFor(model => model.data_tere)

                </div>
            </div>
        </div>
        <div class="modal-footer">
            <a asp-action="Edit" asp-controller="B07_zglo" asp-route-id="@Model.B07_zgloId" class="btn btn-info">Edycja</a>
            <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
        </div>
    </div>
</div>

SM.Web/Views/B07_zglo/Edit.cshtml
@model SM.Web.ViewModels.B07_zgloViewModels.B07_zgloEditViewModel

<form asp-action="Edit" method="post">
    <div>
        <input type="submit" value="Zapisz" class="btn btn-success" />
        <a asp-action="Index" asp-controller="B07_zglo" asp-route-pageIndex="" class="btn btn-default">Powrót</a>
        <a href="#myModalDelete" class="btn btn-danger" data-toggle="modal" style="float: right;">Usuń zgłoszenie</a>
    </div>
    <h3><b>Moduł wprowadzania usterki:</b></h3>
    @Html.HiddenFor(model => model.B07_ZgloDTO.B07_zgloId)
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.id_admin">Administracja</label>
        <select asp-for="B07_ZgloDTO.id_admin" asp-items="@Model.Administracje" class="form-control">
            <option></option>
        </select>
        @if (ViewData?.ModelState["B07_ZgloDTO.id_admin"]?.Errors?.Any() == true)
        {
            <span asp-validation-for="B07_ZgloDTO.id_admin" class="text-danger">Wybór administracji jest wymagany.</span>
        }
    </div>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.numer_zglo">Numer zgłoszenia</label>
        <input asp-for="B07_ZgloDTO.numer_zglo" class="form-control"  readonly/>
        <span asp-validation-for="B07_ZgloDTO.numer_zglo"></span>
    </div>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.id_branz">Branża</label>
        <select asp-for="B07_ZgloDTO.id_branz" asp-items="@Model.Branze" class="form-control">
            <option></option>
        </select>
        <span asp-validation-for="B07_ZgloDTO.id_branz"></span>
    </div>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.data_zglos">Data zgłoszenia</label>
        <input asp-for="B07_ZgloDTO.data_zglos" class="form-control" />
        <span asp-validation-for="B07_ZgloDTO.data_zglos"></span>
    </div>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.nazwisko">Nazwisko zgłaszającego</label>
        <input asp-for="B07_ZgloDTO.nazwisko" class="form-control" />
        <span asp-validation-for="B07_ZgloDTO.nazwisko"></span>
    </div>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.id_adres">Adres</label> <br />
        Aktualny adres: <i id="adres" class="text-muted"></i>
        <input asp-for="B07_ZgloDTO.id_adres" class="form-control" id="id_adres" readonly/>
        <span asp-validation-for="B07_ZgloDTO.id_adres"></span>
        <a href="#myModal" class="btn btn-info btn-sm" data-toggle="modal" style="margin-top: 4px">Wybierz adres</a>
        <br />
    </div>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.rodzaj_ust">Rodzaj usterki</label>
        <input asp-for="B07_ZgloDTO.rodzaj_ust" class="form-control" />
        <span asp-validation-for="B07_ZgloDTO.rodzaj_ust"></span>
    </div>
    <h3><b>Moduł inspektora:</b></h3>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.data_insp">Data akceptacji inspektora</label>
        <input asp-for="B07_ZgloDTO.data_insp" class="form-control" />
        <span asp-validation-for="B07_ZgloDTO.data_insp"></span>
    </div>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.wykonawca">Wykonawca</label>
        <input asp-for="B07_ZgloDTO.wykonawca" class="form-control" />
        <span asp-validation-for="B07_ZgloDTO.wykonawca"></span>
    </div>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.wykon_zewn">Wykonawca zewnętrzny</label>
        <input asp-for="B07_ZgloDTO.wykon_zewn" class="form-control" />
        <span asp-validation-for="B07_ZgloDTO.wykon_zewn"></span>
    </div>
    <h3><b>Moduł wprowadzania usterki:</b></h3>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.numer_zlec">Numer zlecenia</label>
        <input asp-for="B07_ZgloDTO.numer_zlec" class="form-control" />
        <span asp-validation-for="B07_ZgloDTO.numer_zlec"></span>
    </div>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.data_zlec">Data inspekcji</label>
        <input asp-for="B07_ZgloDTO.data_zlec" class="form-control" />
        <span asp-validation-for="B07_ZgloDTO.data_zlec"></span>
    </div>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.uwagi_zlec">Uwagi do zlecenia</label>
        <input asp-for="B07_ZgloDTO.uwagi_zlec" class="form-control" />
        <span asp-validation-for="B07_ZgloDTO.uwagi_zlec"></span>
    </div>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.nr_prac">Pracownik</label>
        <select asp-for="B07_ZgloDTO.nr_prac" asp-items="@Model.Pracownicy" class="form-control">
            <option></option>
        </select>
        <span asp-validation-for="B07_ZgloDTO.nr_prac"></span>
    </div>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.data_wykon">Data wykonania</label>
        <input asp-for="B07_ZgloDTO.data_wykon" class="form-control" />
        <span asp-validation-for="B07_ZgloDTO.data_wykon"></span>
    </div>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.opis_wykon">Opis wykonania</label>
        <input asp-for="B07_ZgloDTO.opis_wykon" class="form-control" />
        <span asp-validation-for="B07_ZgloDTO.opis_wykon"></span>
    </div>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.uwagi_wyko">Uwagi</label>
        <input asp-for="B07_ZgloDTO.uwagi_wyko" class="form-control" />
        <span asp-validation-for="B07_ZgloDTO.uwagi_wyko"></span>
    </div>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.uwagi1">Uwagi dodatkowe</label>
        <input asp-for="B07_ZgloDTO.uwagi1" class="form-control" />
        <span asp-validation-for="B07_ZgloDTO.uwagi1"></span>
    </div>
    <div class="form-group">
        <label asp-for="B07_ZgloDTO.data_tere">Termin realizacji</label>
        <input asp-for="B07_ZgloDTO.data_tere" class="form-control" />
        <span asp-validation-for="B07_ZgloDTO.data_tere"></span>
    </div>



    <div>
        <input type="submit" value="Zapisz" class="btn btn-success"/>
        <a asp-action="Index" asp-controller="B07_zglo" asp-route-pageIndex="" class="btn btn-default">Powrót</a>
        <a href="#myModalDelete" class="btn btn-danger" data-toggle="modal" style="float: right;">Usuń zgłoszenie</a>
    </div>
</form>



<div class="bs-example">
    <div id="myModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Wybór adresu</h4>
                </div>
                <div class="modal-body">
                    @Html.Partial("_AdresDropdownList")
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" onclick="reset()">Zamknij</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal" id="zapisz" onclick="adresToModel()">Zapisz zadres</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="bs-example">
    <div id="myModalDelete" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Usuń zgłoszenie</h4>
                </div>
                <div class="modal-body">
                    Czy na pewno chcesz usunąc zgłoszenie?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Nie</button>
                    <button type="submit" class="btn btn-danger" data-dismiss="modal" onclick="deleteZgloszenie(@Model.B07_ZgloDTO.B07_zgloId)">Tak</button>
                </div>
            </div>
        </div>
    </div>
</div>    



<script type="text/javascript">

    $(function () {
        var adresString = document.getElementById("id_adres").value;
        $.post('@Url.Action("FindAddressFromString")', { adres: adresString }, function (data) {
                $('#adres').html(data);
        });
    });

    function deleteZgloszenie(idPost) {
        var postData = {
            id: idPost
        };
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Delete", "B07_zglo")',
            data: postData,
            dataType: 'json',
            success: function (data) {
                window.location.href = data.url;
            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert('Failed to delete');
            }
        });
    }
</script>       

 

SM.Web/Views/B07_zglo/Index.cshtml
@model SM.Infrastructure.Paging.PagedList<SM.Infrastructure.DTO.B07_zgloDTO>
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";

    var order = Model.OrderAsc ? "glyphicon-menu-up" : "glyphicon-menu-down";
    var numer_zglo_arrow = Model.SortOrder == "numer_zglo" ? "glyphicon" + " " + @order : "";
    var data_zglos_arrow = Model.SortOrder == "data_zglos" ? "glyphicon" + " " + @order : "";
    var data_tere_arrow = Model.SortOrder == "data_tere" ? "glyphicon" + " " + @order : "";
    var nazwisko_arrow = Model.SortOrder == "nazwisko" ? "glyphicon" + " " + @order : "";
    var id_adres_arrow = Model.SortOrder == "id_adres" ? "glyphicon" + " " + @order : "";
    var rodzaj_ust_arrow = Model.SortOrder == "rodzaj_ust" ? "glyphicon" + " " + @order : "";
    var uwagi_wyko_arrow = Model.SortOrder == "uwagi_wyko" ? "glyphicon" + " " + @order : "";
}

<a asp-action="Create" asp-controller="B07_zglo" asp-route-pageIndex="" class="btn btn-success">Utwórz</a>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                <span class="@numer_zglo_arrow"></span>
                <a asp-action="Index" asp-controller="B07_zglo" asp-route-pageIndex="1" asp-route-sortOrder="numer_zglo" asp-route-orderAsc="@(!Model.OrderAsc)" class="text-primary">Nr</a>
            </th>
            <th>
                <span class="@data_zglos_arrow"></span>
                <a asp-action="Index" asp-controller="B07_zglo" asp-route-pageIndex="1" asp-route-sortOrder="data_zglos" asp-route-orderAsc="@(!Model.OrderAsc)" class="text-primary">Data zgłoszenia</a>
            </th>
            <th>
                <span class="@nazwisko_arrow"></span>
                <a asp-action="Index" asp-controller="B07_zglo" asp-route-pageIndex="1" asp-route-sortOrder="nazwisko" asp-route-orderAsc="@(!Model.OrderAsc)" class="text-primary">Nazwisko</a>
            </th>
            <th>
                <span class="@id_adres_arrow"></span>
                <a asp-action="Index" asp-controller="B07_zglo" asp-route-pageIndex="1" asp-route-sortOrder="id_adres" asp-route-orderAsc="@(!Model.OrderAsc)" class="text-primary">Adres</a>
            </th>
            <th>
                <span class="@rodzaj_ust_arrow"></span>
                <a asp-action="Index" asp-controller="B07_zglo" asp-route-pageIndex="1" asp-route-sortOrder="rodzaj_ust" asp-route-orderAsc="@(!Model.OrderAsc)" class="text-primary">Rodzaj zgłoszenia</a>
            </th>
            <th>
                <span class="@uwagi_wyko_arrow"></span>
                <a asp-action="Index" asp-controller="B07_zglo" asp-route-pageIndex="1" asp-route-sortOrder="uwagi_wyko" asp-route-orderAsc="@(!Model.OrderAsc)" class="text-primary">Uwagi</a>
            </th>
            <th>
                <span class="@data_tere_arrow"></span>
                <a asp-action="Index" asp-controller="B07_zglo" asp-route-pageIndex="1" asp-route-sortOrder="data_tere" asp-route-orderAsc="@(!Model.OrderAsc)" class="text-primary">Termin realizacji</a>
            </th>
            <th> Edycja</th>
            <th> Szczegóły</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var B07_zglo in Model.ResultList)
        {
            <tr>
                <td>
                    @B07_zglo.numer_zglo
                </td>
                <td>
                    @B07_zglo.data_zglos
                </td>
                <td>
                    @B07_zglo.nazwisko
                </td>
                <td>
                    @B07_zglo.id_adres
                </td>
                <td>
                    @B07_zglo.rodzaj_ust
                </td>
                <td>
                    @B07_zglo.uwagi_wyko
                </td>
                <td>
                    @B07_zglo.data_tere
                </td>
                <td>
                    <a asp-action="Edit" asp-controller="B07_zglo" asp-route-id="@(B07_zglo.B07_zgloId)" class="glyphicon glyphicon-edit"></a>
                </td>
                <td>
                    <a asp-action="Details" asp-controller="B07_zglo" asp-route-id="@(B07_zglo.B07_zgloId)" data-target="#myModal" class="glyphicon glyphicon-comment" data-toggle="modal" onclick="detailsZgloszenie(@(B07_zglo.B07_zgloId))"></a>
                </td>
            </tr>
        }
    </tbody>
</table>

@Model.PageIndex
@Model.SortOrder
@Model.OrderAsc
<a asp-action="Index" asp-controller="B07_zglo" asp-route-pageIndex="1" asp-route-sortOrder="@Model.SortOrder" asp-route-orderAsc="@Model.OrderAsc" class="btn btn-default">Pierwsza</a>
<a asp-action="Index" asp-controller="B07_zglo" asp-route-pageIndex="@(Model.PageIndex - 1)" asp-route-sortOrder="@Model.SortOrder" asp-route-orderAsc="@Model.OrderAsc" class="btn btn-default @prevDisabled">Poprzednia</a>
<a asp-action="Index" asp-controller="B07_zglo" asp-route-pageIndex="@(Model.PageIndex + 1)" asp-route-sortOrder="@Model.SortOrder" asp-route-orderAsc="@Model.OrderAsc" class="btn btn-default @nextDisabled">Następna</a>
<a asp-action="Index" asp-controller="B07_zglo" asp-route-pageIndex="@(Model.TotalPages)" asp-route-sortOrder="@Model.SortOrder" asp-route-orderAsc="@Model.OrderAsc" class="btn btn-default">Ostatnia</a>

<!-- Modal Details -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div id="modalAjax"></div>
    </div>
</div>

<script type="text/javascript">

    function detailsZgloszenie(idGet) {
        $.ajax({
            url: "/B07_zglo/Details/" + idGet,
            type: "GET",
            success: function (data) {
                $("#modalAjax").html(data);
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Problem podczas wczytywania szczegółów!");
            }
        });

    }
</script>